# Generated by Django 5.0.6 on 2024-08-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='amount',
            new_name='quantity',
        ),
    ]
