# Generated by Django 5.0.6 on 2024-07-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_recipient_name_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultrecipient',
            old_name='address',
            new_name='recipient_address',
        ),
        migrations.RenameField(
            model_name='defaultrecipient',
            old_name='phone_number',
            new_name='recipient_phone_number',
        ),
    ]
