# Generated by Django 5.0.6 on 2024-08-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
