# Generated by Django 5.0.6 on 2024-07-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='類型標題')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goodstype', verbose_name='類型圖片')),
                ('desc', models.TextField(verbose_name='類型描述')),
            ],
            options={
                'verbose_name': '商品類型',
                'verbose_name_plural': '商品類型',
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11)),
                ('upwd', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='商品名稱')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='商品價格')),
                ('spec', models.CharField(max_length=20, verbose_name='商品規格')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goods', verbose_name='商品圖片')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否上架')),
                ('goodsType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goodstype', verbose_name='商品類型')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='ccount')),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='shop.goods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車',
                'db_table': 'cart_info',
            },
        ),
    ]
