# Generated by Django 5.0.6 on 2024-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(null=True, upload_to='upload/goods', verbose_name='商品圖片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(null=True, upload_to='upload/goodstype', verbose_name='類型圖片'),
        ),
    ]
