# Generated by Django 5.0.6 on 2024-07-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_goods_picture_alter_goodstype_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartInfo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
