# Generated by Django 5.0.6 on 2024-07-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_goodstype_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsType',
        ),
    ]
