# Generated by Django 5.0.6 on 2024-07-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
