# Generated by Django 5.0.6 on 2024-08-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
