# Generated by Django 5.0.6 on 2024-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_center', '0002_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_method',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('line', 'Line'), ('facebook', 'Facebook')], default='local', max_length=50),
        ),
    ]
